apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: data-platform-api-product-master-reads-rmq-kube
  name: data-platform-api-product-master-reads-rmq-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      run: data-platform-api-product-master-reads-rmq-kube
  template:
    metadata:
      labels:
        run: data-platform-api-product-master-reads-rmq-kube
    spec:
      hostname: data-platform-api-product-master-reads-rmq-kube
      containers:
        - name: data-platform-api-product-master-reads-rmq-kube
          image: latonaio/data-platform-api-product-master-reads-rmq-kube
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /var/lib/aion/Data
            - name: ui
              mountPath: /var/lib/aion/UI/data-platform-api-product-master-reads-rmq-kube/public/
          env:
            - name: RMQ_USER
              value: "guest"
            - name: RMQ_PASS
              value: "guest"
            - name: RMQ_ADDRESS
              value: "192.168.128.135"
            - name: RMQ_PORT
              value: "32094"
            - name: RMQ_VHOST
              value: "sap-test"
            - name: RMQ_QUEUE_FROM
              value: "data-platform-api-product-master-reads-rmq-kube"
            - name: RMQ_QUEUE_TO
              value: "data-platform-sql-updates-rmq-kube"
            - name: DPFM_API_BASE_URL
              value: "https://XXX.XX.XX.XXX:8080/dpfm/opu/odata/dpfm/"
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"
      volumes:
        - name: data
          hostPath:
            path: /var/lib/aion/default/Data
        - name: ui
          hostPath:
            path: /var/lib/aion/UI/data-platform-api-product-master-reads-rmq-kube/public/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: data-platform-api-product-master-reads-rmq-kube
  name: data-platform-api-product-master-reads-rmq-kube
spec:
  selector:
    run: data-platform-api-product-master-reads-rmq-kube
  type: NodePort
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30512
